---
apiVersion: v1
kind: Service
metadata:
  name: mds-web-service
spec:
  selector:
    app: mds-web
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: mds-web-ing
  namespace: default
spec:
  rules:
  - host: mds-web.mti
    http:
      paths:
      - path: /
        backend:
          serviceName: mds-web-service
          servicePort: 80